"""Mutation pass: break every safety property on purpose, confirm a test notices.

Passing tests prove nothing on their own. Each entry below is a small edit to the
contract that removes a defence. The suite must fail for every one of them, and
this script records WHICH test caught it, so the table in the README is measured
rather than claimed.

    python scripts/mutate.py            # run them all, print what caught what
    python scripts/mutate.py --md       # emit the markdown table for the README

An escaping mutation is a finding, not a nuisance. It means either a missing
test, or a later defence strict enough to cover a case an earlier test was
supposed to catch -- which leaves that earlier test unable to fail. A test that
cannot fail is worse than no test, because it reports coverage it does not
provide.
"""

import argparse
import pathlib
import re
import shutil
import subprocess
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
TARGET = "recant.py"

# (label, find, replace) -- or (label, ((find, replace), ...), None) for the
# few that only become observable when two defences go at once.
MUTATIONS = [
    (
        "the layer 1 structural check removed",
        "    if not structurally_sound(their_indices, scope_size, self_index):\n        return False\n",
        "",
    ),
    (
        "agreement loosened to \"both found something\"",
        "    return sorted(mine[\"indices\"]) == sorted(their_indices)",
        "    return (len(mine[\"indices\"]) > 0) == (len(their_indices) > 0)",
    ),
    (
        "unparseable output read as clean",
        "    if raw not in (\"\", NONE) and len(their_indices) == 0:\n        return False                      # unparseable, not merely empty\n",
        "",
    ),
    (
        "a statement allowed to contradict itself",
        "    if self_index in indices:\n        return False\n",
        "",
    ),
    (
        "out of range indices allowed",
        "        if i < 0 or i >= scope_size:\n            return False",
        "        if False:\n            return False",
    ),
    (
        "duplicates accepted by the parser",
        "    return len(set(indices)) == len(indices)",
        "    return True",
    ),
    (
        "the reason sanitiser disabled",
        "        if ch in \"<>{}\\\\`\":\n            continue\n",
        "",
    ),
    (
        "control characters left in reasons",
        "        if ord(ch) < 32 or ord(ch) == 127:\n            ch = \" \"\n",
        "",
    ),
    (
        "non-numeric accepted by the parser",
        "        if part == \"\" or not part.isdigit():\n            return []",
        "        if part == \"\":\n            return []",
    ),
    (
        "withdrawn statements treated as live",
        "    live = [i for i in indices if i < len(live_flags) and live_flags[i]]",
        "    live = [i for i in indices if i < len(live_flags)]",
    ),
    (
        "a multi-way conflict collapsed to one",
        "    return CONFLICT, sorted(live)",
        "    return CONTRADICTS, sorted(live)[:1]",
    ),
    (
        "`stale` collapsed into `contradicts`",
        "    if len(live) == 0:\n        return STALE, sorted(indices)",
        "    if len(live) == 0:\n        return CONTRADICTS, sorted(indices)",
    ),
    (
        "an empty answer read as a contradiction rather than clear",
        "    if len(indices) == 0:\n        return CLEAR, []",
        "    if len(indices) == 0:\n        return CONTRADICTS, []",
    ),
    (
        "later statements pulled into scope",
        "            if i >= limit:\n                break\n",
        "",
    ),
    (
        "the author filter dropped from scope",
        "            if int(s.author_id) == target:",
        "            if True:",
    ),
    (
        "the scope cap removed, so an unbounded prompt is built",
        "        return out[-MAX_SCOPE:]",
        "        return out",
    ),
    (
        "the view bounds check removed",
        "        if i < 0 or i >= len(self.statements):\n            raise gl.vm.UserError(\"no such statement\")\n",
        "",
    ),
    (
        "negative ids allowed through to Python list indexing",
        "        if i < 0 or i >= len(self.statements):",
        "        if i >= len(self.statements):",
    ),
    # -- the lifted copy. lib/recant_consensus.py claims to be these rules as
    # -- the contract runs them, so an edit on one side has to fail the suite.
    # -- It drifted once already: the lib kept an UNFENCED build_prompt after
    # -- the contract was fixed, so the file offered "to be copied" carried the
    # -- injection bug. Generated by scripts/lift.py now, and compared here.
    (
        "the contract edited without regenerating the lifted copy",
        "def in_scope(indices, scope_size):",
        "def in_scope(indices, scope_size):\n    indices = list(indices)",
    ),

    # -- recourse. An adverse verdict has to leave the author somewhere to go.
    (
        "a contradiction blocks any further statement on the record",
        "        a.n_statements = a.n_statements + u256(1)",
        "        if int(a.n_contradicts) > 0:\n"
        "            raise gl.vm.UserError(\"record closed\")\n"
        "        a.n_statements = a.n_statements + u256(1)",
    ),
    (
        "withdrawing a marked statement erases its verdict",
        "        s.withdrawn = True",
        "        s.withdrawn = True\n        s.verdict = \"\"",
    ),
    (
        "anyone allowed to withdraw",
        "        if gl.message.sender_address != a.registrar:\n            raise gl.vm.UserError(\"only the registrar may withdraw a statement\")\n",
        "",
    ),
    (
        "re-checking allowed, so a verdict can be overwritten",
        "        if bool(s.checked):\n            raise gl.vm.UserError(\"already checked\")\n",
        "",
    ),
    (
        "withdrawing twice allowed",
        "        if bool(s.withdrawn):\n            raise gl.vm.UserError(\"already withdrawn\")\n",
        "",
    ),
    # -- authority. The rejection that made this section exist: state() shipped
    # -- with no sender check at all, so any account could put words on any
    # -- record. Every defence added in response gets a mutation here.
    (
        "state left unauthenticated, so anyone may write to any record",
        "        if not self._may_state(author_id, a, gl.message.sender_address):\n"
        "            raise gl.vm.UserError(\n"
        "                \"only the registrar or an authorised delegate may add to this record\"\n"
        "            )\n",
        "",
    ),
    (
        "the submitting address not recorded on the statement",
        "                by=gl.message.sender_address,\n",
        "                by=a.registrar,\n",
    ),
    (
        "a revoked delegate still counted as authorised",
        "            if int(d.author_id) == target and d.who == who and bool(d.active):",
        "            if int(d.author_id) == target and d.who == who:",
    ),
    (
        "delegation not scoped to the record it was granted on",
        "            if int(d.author_id) == target and d.who == who and bool(d.active):",
        "            if d.who == who and bool(d.active):",
    ),
    (
        "a delegate allowed to appoint further delegates",
        "        if gl.message.sender_address != a.registrar:\n"
        "            raise gl.vm.UserError(\"only the registrar may authorise a delegate\")",
        "        if not self._may_state(author_id, a, gl.message.sender_address):\n"
        "            raise gl.vm.UserError(\"only the registrar may authorise a delegate\")",
    ),
    (
        "a delegate allowed to revoke",
        "        if gl.message.sender_address != a.registrar:\n"
        "            raise gl.vm.UserError(\"only the registrar may revoke a delegate\")",
        "        if not self._may_state(author_id, a, gl.message.sender_address):\n"
        "            raise gl.vm.UserError(\"only the registrar may revoke a delegate\")",
    ),
    (
        "may_state() drifting from the rule state() enforces",
        "        a = self._author(author_id)\n"
        "        return self._may_state(author_id, a, Address(str(who).strip()))",
        "        self._author(author_id)\n"
        "        return True",
    ),
    (
        "the cap not re-checked when a revoked delegate is reactivated",
        "            if live >= MAX_DELEGATES:\n"
        "                raise gl.vm.UserError(\n"
        "                    f\"a record is capped at {MAX_DELEGATES} active delegates\"\n"
        "                )\n"
        "            row.active = True",
        "            row.active = True",
    ),
    (
        "the cap counted in the same pass that finds the row",
        "            if d.who == addr:\n"
        "                found = i\n",
        "            if d.who == addr:\n"
        "                found = i\n"
        "                break\n",
    ),
    (
        "the delegate cap removed",
        "        if live >= MAX_DELEGATES:",
        "        if False:",
    ),
    (
        "a malformed delegate address passed to Address()",
        "        if not looks_like_address(who):\n"
        "            raise gl.vm.UserError(\"that is not a 20 byte hex address\")\n"
        "        addr = Address(str(who).strip())\n"
        "        if addr == a.registrar:",
        "        addr = Address(str(who).strip())\n"
        "        if addr == a.registrar:",
    ),
    # NOT listed: "the post-consensus range check dropped". By the time the
    # deterministic half runs, leader_fn has already clamped an out-of-range
    # answer to empty AND the validator's layer 1 has rejected one that arrived
    # out of range anyway. Removing the check changes no outcome, so no test can
    # catch it and claiming one would be a lie. It stays in the contract as
    # defence in depth. See DECISIONS.md.
    # -- the prompt boundary. Tagging untrusted text and telling the model it is
    # -- data is not a fence unless the characters that close a tag go too.
    (
        "the prompt fence removed, so a caller can forge a block",
        '    return str(raw).replace("<", "(").replace(">", ")")',
        "    return str(raw)",
    ),
    (
        "the fence deletes instead of replacing",
        '    return str(raw).replace("<", "(").replace(">", ")")',
        '    return str(raw).replace("<", "").replace(">", "")',
    ),
    (
        "only the opening bracket fenced",
        '    return str(raw).replace("<", "(").replace(">", ")")',
        '    return str(raw).replace("<", "(")',
    ),
    (
        "the statement reaches the model unfenced",
        "{fence(subject)}",
        "{subject}",
    ),
    (
        "the record block reaches the model unfenced",
        "{fence(numbered_scope)}",
        "{numbered_scope}",
    ),
    (
        "a nested mapping returned from the block",
        "                \"because\": sanitise_reason(out.get(\"because\", \"\")),",
        "                \"because\": {\"text\": sanitise_reason(out.get(\"because\", \"\"))},",
    ),
    (
        "a bool returned from the block",
        "                \"indices\": \"|\".join(str(i) for i in idx) if idx else NONE,",
        "                \"found\": len(idx) > 0,\n                \"indices\": \"|\".join(str(i) for i in idx) if idx else NONE,",
    ),
    (
        "a collection nested back into a storage dataclass",
        "@allow_storage\n@dataclass\nclass Statement:\n    author_id: u256",
        "@allow_storage\n@dataclass\nclass Statement:\n    tags: DynArray[str]\n    author_id: u256",
    ),
    (
        "an int storage field",
        "    author_id: u256\n    by: Address",
        "    author_id: int\n    by: Address",
    ),
    (
        "a storage field declared twice",
        "    authors: DynArray[Author]\n    statements: DynArray[Statement]",
        "    authors: DynArray[Author]\n    statements: DynArray[Statement]\n    statements: DynArray[Statement]",
    ),
]


def apply_edits(src, spec):
    edits = spec if isinstance(spec, tuple) and isinstance(spec[0], tuple) else ((spec[0], spec[1]),)
    for find, repl in edits:
        if find not in src:
            return None
        src = src.replace(find, repl, 1)
    return src


def run_one(label, find, replace):
    with tempfile.TemporaryDirectory() as tmp:
        dst = pathlib.Path(tmp) / "repo"
        shutil.copytree(
            ROOT, dst,
            ignore=shutil.ignore_patterns("__pycache__", ".pytest_cache", ".git",
                                          "artifacts", "*.pyc"),
        )
        target = dst / "contracts" / TARGET
        src = target.read_text(encoding="utf-8")
        spec = find if isinstance(find, tuple) else (find, replace)
        out = apply_edits(src, spec)
        if out is None:
            return "PATTERN NOT FOUND", None
        target.write_text(out, encoding="utf-8")

        proc = subprocess.run(
            [sys.executable, "-m", "pytest", "tests/", "-x", "-q",
             "--no-header", "-p", "no:cacheprovider"],
            cwd=dst, capture_output=True, text=True,
        )
        if proc.returncode == 0:
            return "ESCAPED", None

        text = proc.stdout + proc.stderr
        # A collection error counts as caught: a contract that will not import
        # is a contract that will not deploy.
        m = re.search(r"^(?:FAILED|ERROR) (\S+?)::(\S+?)(?:\[|\s|$)", text, re.M)
        if m:
            return "caught", m.group(2).split("::")[-1]
        m = re.search(r"^E\s+(\w*(?:Error|Exception))", text, re.M)
        if m:
            return "caught", m.group(1) + " at import"
        return "caught", "unnamed failure"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--md", action="store_true", help="emit the README table")
    args = ap.parse_args()

    rows, escaped = [], []
    for label, find, replace in MUTATIONS:
        status, test = run_one(label, find, replace)
        if status == "caught":
            rows.append((label, test))
            if not args.md:
                print("  caught   %-56s %s" % (label, test))
        else:
            escaped.append((label, status))
            print("  %-8s %s" % (status, label), file=sys.stderr)

    if args.md:
        print("| Mutation | Caught by |")
        print("|---|---|")
        for label, test in rows:
            print("| %s | `%s` |" % (label, test))
    else:
        print()
        print("  %d mutations, %d caught, %d escaped"
              % (len(MUTATIONS), len(rows), len(escaped)))

    return 1 if escaped else 0


if __name__ == "__main__":
    sys.exit(main())
